export const TECH_ALIASES: Record<string, string> = {
  // ── Node / JavaScript ──────────────────────────────────────────────────────
  'node': 'nodejs',
  'node.js': 'nodejs',
  'nodejs': 'nodejs',
  'node js': 'nodejs',
  'javascript': 'javascript',
  'js': 'javascript',
  'es6': 'javascript',
  'es2015': 'javascript',
  'vanilla js': 'javascript',
  'typescript': 'typescript',
  'ts': 'typescript',
  'type script': 'typescript',

  // ── React ─────────────────────────────────────────────────────────────────
  'react': 'react',
  'react.js': 'react',
  'reactjs': 'react',
  'react js': 'react',
  'react native': 'react-native',
  'reactnative': 'react-native',
  'rn': 'react-native',
  'react hooks': 'react',
  'redux': 'redux',
  'react redux': 'redux',
  'zustand': 'zustand',
  'recoil': 'recoil',

  // ── Next.js ───────────────────────────────────────────────────────────────
  'next': 'nextjs',
  'next.js': 'nextjs',
  'nextjs': 'nextjs',
  'next js': 'nextjs',
  'next.js 13': 'nextjs',
  'next.js 14': 'nextjs',
  'next.js 15': 'nextjs',
  'app router': 'nextjs',

  // ── NestJS ────────────────────────────────────────────────────────────────
  'nest': 'nestjs',
  'nest.js': 'nestjs',
  'nestjs': 'nestjs',
  'nest js': 'nestjs',
  'nestjsframework': 'nestjs',

  // ── Python ────────────────────────────────────────────────────────────────
  'python': 'python',
  'python3': 'python',
  'python 3': 'python',
  'py': 'python',
  'fastapi': 'fastapi',
  'fast api': 'fastapi',
  'flask': 'flask',
  'django': 'django',
  'django rest framework': 'django',
  'drf': 'django',
  'aiohttp': 'python',
  'tornado': 'python',

  // ── AI / ML ───────────────────────────────────────────────────────────────
  'ai': 'ai',
  'artificial intelligence': 'ai',
  'machine learning': 'ml',
  'ml': 'ml',
  'deep learning': 'ml',
  'neural network': 'ml',
  'neural networks': 'ml',
  'generative ai': 'generative-ai',
  'gen ai': 'generative-ai',
  'genai': 'generative-ai',
  'generativeai': 'generative-ai',
  'llm': 'generative-ai',
  'llms': 'generative-ai',
  'large language model': 'generative-ai',
  'gpt': 'generative-ai',
  'openai': 'generative-ai',
  'langchain': 'generative-ai',
  'rag': 'generative-ai',
  'retrieval augmented generation': 'generative-ai',
  'nlp': 'ml',
  'natural language processing': 'ml',
  'computer vision': 'ml',
  'cv': 'ml',
  'tensorflow': 'ml',
  'pytorch': 'ml',
  'scikit-learn': 'ml',
  'sklearn': 'ml',
  'hugging face': 'generative-ai',
  'huggingface': 'generative-ai',
  'transformers': 'generative-ai',

  // ── Frontend (general) ────────────────────────────────────────────────────
  'frontend': 'frontend',
  'front end': 'frontend',
  'front-end': 'frontend',
  'ui development': 'frontend',
  'ui engineer': 'frontend',
  'vue': 'vuejs',
  'vue.js': 'vuejs',
  'vuejs': 'vuejs',
  'vue js': 'vuejs',
  'nuxt': 'nuxtjs',
  'nuxt.js': 'nuxtjs',
  'nuxtjs': 'nuxtjs',
  'angular': 'angular',
  'angular.js': 'angularjs',
  'angularjs': 'angularjs',
  'svelte': 'svelte',
  'sveltekit': 'svelte',
  'astro': 'astro',
  'remix': 'remix',
  'tailwind': 'tailwindcss',
  'tailwindcss': 'tailwindcss',
  'tailwind css': 'tailwindcss',
  'css': 'css',
  'html': 'html',
  'html5': 'html',
  'css3': 'css',
  'sass': 'css',
  'scss': 'css',
  'storybook': 'storybook',
  'vite': 'vite',
  'webpack': 'webpack',
  'babel': 'javascript',
  'jest': 'jest',
  'cypress': 'cypress',
  'playwright': 'playwright',

  // ── Backend (general) ─────────────────────────────────────────────────────
  'backend': 'backend',
  'back end': 'backend',
  'back-end': 'backend',
  'server side': 'backend',
  'server-side': 'backend',
  'api development': 'backend',
  'rest api': 'backend',
  'restful': 'backend',
  'rest': 'backend',
  'graphql': 'graphql',
  'graph ql': 'graphql',
  'grpc': 'grpc',
  'express': 'expressjs',
  'express.js': 'expressjs',
  'expressjs': 'expressjs',
  'koa': 'nodejs',
  'hapi': 'nodejs',
  'fastify': 'fastify',
  'microservices': 'microservices',
  'micro services': 'microservices',
  'event driven': 'microservices',
  'message queue': 'microservices',
  'kafka': 'kafka',
  'rabbitmq': 'rabbitmq',
  'redis': 'redis',

  // ── Fullstack ─────────────────────────────────────────────────────────────
  'fullstack': 'fullstack',
  'full stack': 'fullstack',
  'full-stack': 'fullstack',
  'mern': 'fullstack',
  'mean': 'fullstack',
  'mevn': 'fullstack',
  't3 stack': 'fullstack',

  // ── Databases ─────────────────────────────────────────────────────────────
  'mongodb': 'mongodb',
  'mongo': 'mongodb',
  'mongo db': 'mongodb',
  'postgresql': 'postgresql',
  'postgres': 'postgresql',
  'pg': 'postgresql',
  'mysql': 'mysql',
  'sql': 'sql',
  'sqlite': 'sql',
  'prisma': 'prisma',
  'sequelize': 'sql',
  'typeorm': 'typeorm',
  'drizzle': 'sql',
  'supabase': 'postgresql',
  'dynamodb': 'dynamodb',
  'dynamo db': 'dynamodb',
  'firebase': 'firebase',
  'firestore': 'firebase',
  'elasticsearch': 'elasticsearch',
  'elastic search': 'elasticsearch',
  'pinecone': 'vector-db',
  'weaviate': 'vector-db',
  'chroma': 'vector-db',
  'qdrant': 'vector-db',

  // ── Cloud / DevOps ────────────────────────────────────────────────────────
  'aws': 'aws',
  'amazon web services': 'aws',
  'gcp': 'gcp',
  'google cloud': 'gcp',
  'google cloud platform': 'gcp',
  'azure': 'azure',
  'microsoft azure': 'azure',
  'docker': 'docker',
  'kubernetes': 'kubernetes',
  'k8s': 'kubernetes',
  'terraform': 'terraform',
  'ci/cd': 'devops',
  'devops': 'devops',
  'github actions': 'devops',
  'jenkins': 'devops',
  'serverless': 'serverless',
  'lambda': 'aws',
  'vercel': 'vercel',
  'netlify': 'netlify',

  // ── Mobile ────────────────────────────────────────────────────────────────
  'ios': 'ios',
  'swift': 'ios',
  'android': 'android',
  'kotlin': 'android',
  'flutter': 'flutter',
  'dart': 'flutter',
};

export function normalizeTechTags(tags: string[]): string[] {
  return tags.map(t => {
    const lower = t.toLowerCase().trim();
    return TECH_ALIASES[lower] ?? lower;
  });
}
